// [English, 中文] names per PriceCatcher item_code, for the items priced in Sep 2026.
// Items missing here fall back to the official Malay name. Brand names stay as printed on the pack.
export const ITEMS = {
  1: ['Chicken, cleaned (standard)', '光鸡（标准）'],
  2: ['Chicken, cleaned (super)', '光鸡（特级）'],
  9: ['Imported mutton, bone-in (Australia, boxed)', '进口羊肉带骨（澳洲，盒装）'],
  10: ['Imported mutton, bone-in (New Zealand, boxed)', '进口羊肉带骨（新西兰，盒装）'],
  11: ['Imported mutton, boneless, no leg (Australia)', '进口无骨羊肉，不含腿（澳洲）'],
  12: ['Imported mutton, boneless, no leg (New Zealand)', '进口无骨羊肉，不含腿（新西兰）'],
  14: ['Imported buffalo meat, topside (India)', '进口水牛肉 Topside（印度）'],
  16: ['Papaya', '木瓜'],
  18: ['Banana (berangan)', '香蕉（Berangan）'],
  19: ['Banana (emas)', '皇帝蕉'],
  20: ['Red watermelon, seeded', '红肉西瓜（有籽）'],
  21: ['Red watermelon, seedless', '红肉西瓜（无籽）'],
  22: ['Red dragon fruit', '红肉火龙果'],
  24: ['Honeydew melon', '蜜瓜'],
  25: ['Pineapple', '黄梨'],
  26: ['Green grapes, seeded', '青葡萄（有籽）'],
  27: ['Red grapes, seeded', '红葡萄（有籽）'],
  31: ['Yellow pear (size M)', '鸭梨（M号）'],
  38: ['Guava, seeded', '番石榴（有籽）'],
  39: ['Guava, seedless', '番石榴（无籽）'],
  43: ['Black pomfret fish', '黑鲳鱼'],
  47: ['Torpedo scad fish (cencaru)', '硬尾鱼'],
  52: ['Grouper fish head', '石斑鱼头'],
  55: ['Small Indian mackerel (kembung)', '小甘望鱼'],
  64: ['Red snapper fish head', '红鱼头'],
  69: ['Yellowstripe scad fish (selar kuning)', '黄带鲹'],
  70: ['Scad fish, large (selar)', '鲹鱼（大）'],
  88: ['Catfish (keli)', '塘虱鱼'],
  92: ['Green chilli', '青辣椒'],
  93: ['Red chilli (kulai)', '红辣椒（Kulai）'],
  94: ['Red chilli (minyak)', '红辣椒（Minyak）'],
  95: ['Ginger, mature', '老姜'],
  96: ['Okra (lady\'s fingers)', '羊角豆'],
  97: ['French beans', '四季豆'],
  98: ['Long beans', '长豆'],
  101: ['Coconut, whole', '椰子'],
  102: ['Grated coconut', '椰丝'],
  103: ['Fresh coconut milk (regular)', '新鲜椰浆（普通）'],
  104: ['Cabbage, imported (China)', '包菜（中国进口）'],
  105: ['Cabbage, local', '包菜（本地）'],
  108: ['Fresh turmeric', '黄姜'],
  109: ['Carrot', '红萝卜'],
  113: ['Cucumber', '黄瓜'],
  114: ['Tomato', '番茄'],
  118: ['Chicken eggs, grade A', '鸡蛋 A级'],
  119: ['Chicken eggs, grade B', '鸡蛋 B级'],
  120: ['Chicken eggs, grade C', '鸡蛋 C级'],
  129: ['Yellow onion (Holland)', '黄洋葱（荷兰）'],
  131: ['Rose shallots, imported (India)', '小红葱（印度 Rose）'],
  132: ['Shallots, imported (Thailand)', '小红葱（泰国）'],
  180: ['BOH tea bags', 'BOH 茶包'],
  191: ['Ayam Brand sardines in tomato sauce', 'Ayam Brand 雄鸡标番茄沙丁鱼'],
  193: ['King Cup sardines in tomato sauce', 'King Cup 番茄沙丁鱼'],
  201: ['Lady\'s Choice strawberry jam', 'Lady\'s Choice 草莓果酱'],
  203: ['Mainland Chesdale cheddar cheese slices', 'Mainland Chesdale 切达芝士片'],
  205: ['Daisy margarine', 'Daisy 人造牛油'],
  206: ['Planta margarine', 'Planta 人造牛油'],
  214: ['Kipas Udang sweet soy sauce', 'Kipas Udang 甜酱油'],
  217: ['Maggi tomato ketchup', '美极番茄酱'],
  218: ['Life chilli sauce', 'Life 辣椒酱'],
  221: ['Drinho soy milk (carton)', 'Drinho 豆奶（盒装）'],
  224: ['Dutch Lady fresh milk', '子母牌鲜奶'],
  226: ['Yeo\'s lychee drink (carton)', '杨协成荔枝饮料（盒装）'],
  228: ['Coca-Cola soda (bottle)', '可口可乐（瓶装）'],
  229: ['F&N orange soda (can)', 'F&N 橙味汽水（罐装）'],
  230: ['F&N orange soda (bottle)', 'F&N 橙味汽水（瓶装）'],
  232: ['Mirinda orange soda (bottle)', 'Mirinda 橙味汽水（瓶装）'],
  235: ['Marigold Peel Fresh orange juice', 'Marigold Peel Fresh 橙汁'],
  239: ['Red Bull energy drink (bottle)', '红牛（瓶装）'],
  240: ['Livita energy drink with honey (bottle)', 'Livita 蜂蜜饮料（瓶装）'],
  246: ['Mazola corn oil', 'Mazola 粟米油'],
  254: ['Red Eagle blended cooking oil', '红鹰牌混合食用油'],
  260: ['Knife blended cooking oil', '刀标混合食用油'],
  263: ['Buruh palm cooking oil', 'Buruh 纯棕榈食用油'],
  266: ['Seri Murni palm cooking oil', 'Seri Murni 纯食用油'],
  267: ['Vesawit palm cooking oil', 'Vesawit 纯食用油'],
  271: ['QBB ghee', 'QBB 酥油'],
  292: ['Colgate toothpaste (fresh mint)', '高露洁牙膏（清新薄荷）'],
  293: ['Darlie Double Action toothpaste', '黑人双重薄荷牙膏'],
  295: ['Fresh & White toothpaste (fresh mint)', 'Fresh & White 牙膏（清新薄荷）'],
  299: ['Lactogen 1 infant formula', 'Lactogen 1 婴儿配方奶粉'],
  300: ['Lactogen 2 follow-on formula', 'Lactogen 2 较大婴儿配方奶粉'],
  350: ['Babas fish curry powder', 'Babas 鱼咖喱粉'],
  364: ['Babas chilli powder', 'Babas 辣椒粉'],
  365: ['Adabi turmeric powder', 'Adabi 黄姜粉'],
  368: ['Peanuts, imported', '花生（进口）'],
  716: ['Green bird\'s eye chilli', '青指天椒'],
  845: ['Squid', '苏东（鱿鱼）'],
  847: ['Flower crab', '花蟹'],
  849: ['Small white prawns', '小白虾'],
  850: ['Tiger prawns', '老虎虾'],
  861: ['Potatoes (Holland)', '马铃薯（荷兰）'],
  869: ['Mustard seeds', '芥菜籽'],
  883: ['F&N sweetened creamer', 'F&N 甜炼奶'],
  884: ['Gold Coin sweetened creamer', '金币牌甜炼奶'],
  904: ['Rambutan super rice 5% (imported)', '红毛丹牌超级白米 5%（进口）'],
  910: ['F&N cordial (assorted flavours)', 'F&N 浓缩饮料（多种口味）'],
  917: ['Sauh wheat flour', '锚标面粉'],
  918: ['Cooking oil packet (assorted brands)', '袋装食用油（多品牌）'],
  929: ['Nescafe Classic coffee (refill pack)', '雀巢经典咖啡（补充装）'],
  992: ['Jati rice 5%', 'Jati 白米 5%'],
  1070: ['Maggi chilli sauce', '美极辣椒酱'],
  1086: ['Daisy corn oil', 'Daisy 粟米油'],
  1087: ['Daisy corn oil', 'Daisy 粟米油'],
  1088: ['Mazola corn oil', 'Mazola 粟米油'],
  1089: ['Vecorn corn oil', 'Vecorn 粟米油'],
  1090: ['Vecorn corn oil', 'Vecorn 粟米油'],
  1091: ['Red Eagle blended cooking oil', '红鹰牌混合食用油'],
  1093: ['Knife blended cooking oil', '刀标混合食用油'],
  1094: ['Buruh palm cooking oil', 'Buruh 纯棕榈食用油'],
  1095: ['Vesawit palm cooking oil', 'Vesawit 纯食用油'],
  1100: ['Seri Murni palm cooking oil', 'Seri Murni 纯食用油'],
  1101: ['Seri Murni palm cooking oil', 'Seri Murni 纯食用油'],
  1109: ['Chicken eggs, grade A', '鸡蛋 A级'],
  1110: ['Chicken eggs, grade B', '鸡蛋 B级'],
  1111: ['Chicken eggs, grade C', '鸡蛋 C级'],
  1128: ['Green capsicum (bell pepper)', '青灯笼椒'],
  1131: ['Potatoes, imported (China)', '马铃薯（中国）'],
  1132: ['Lime', '青柠'],
  1135: ['Adabi sweet soy sauce', 'Adabi 甜酱油'],
  1138: ['Maggi oyster sauce', '美极蚝油'],
  1142: ['Adabi sardines in chilli tomato sauce', 'Adabi 辣味番茄沙丁鱼'],
  1144: ['Lady\'s Choice smooth peanut butter', 'Lady\'s Choice 幼滑花生酱'],
  1145: ['Nestle Cerelac rice cereal (tin)', '雀巢 Cerelac 米糊（罐装）'],
  1151: ['Ayam Brand coconut milk', 'Ayam Brand 雄鸡标椰浆'],
  1153: ['Adabi tom yam paste', 'Adabi 冬炎酱'],
  1355: ['100 Plus isotonic drink', '100 Plus 原味'],
  1367: ['Imported mutton leg, bone-in (Australia)', '进口羊腿带骨（澳洲）'],
  1368: ['Imported mutton leg, bone-in (New Zealand)', '进口羊腿带骨（新西兰）'],
  1369: ['Local mutton, bone-in', '本地羊肉带骨'],
  1370: ['Imported beef, topside', '进口牛肉 Topside'],
  1371: ['Imported beef, blade', '进口牛肉 Blade'],
  1372: ['Imported beef, chuck tender', '进口牛肉 Chuck tender'],
  1373: ['Imported beef, knuckle', '进口牛肉 Knuckle'],
  1375: ['Imported buffalo meat, silverside (India)', '进口水牛肉 Silverside（印度）'],
  1376: ['Imported buffalo meat, rump (India)', '进口水牛肉 Rump（印度）'],
  1377: ['Imported buffalo meat, blade (India)', '进口水牛肉 Blade（印度）'],
  1378: ['Imported buffalo meat, chuck (India)', '进口水牛肉 Chuck（印度）'],
  1379: ['Pork belly', '五花肉'],
  1380: ['Pork, lean and fat', '猪肉（肥瘦）'],
  1391: ['Large white prawns (41–60/kg)', '大白虾（每公斤41–60只）'],
  1396: ['Cabbage, imported (Indonesia)', '包菜（印尼进口）'],
  1399: ['Leek, local', '青蒜（本地）'],
  1400: ['Leek, imported', '青蒜（进口）'],
  1412: ['Chinese cabbage, large (China)', '大白菜（中国，大）'],
  1419: ['Dal lentils (India)', 'Dal 扁豆（印度）'],
  1420: ['Dal lentils, Malawi (India)', 'Dal 扁豆 Malawi（印度）'],
  1422: ['Dal lentils (Australia)', 'Dal 扁豆（澳洲）'],
  1431: ['Local beef, leg cuts', '本地牛肉（腿肉）'],
  1432: ['Local beef, lean cuts', '本地牛肉（精肉）'],
  1436: ['Threadfin bream fish (kerisi)', '金线鱼'],
  1437: ['Sea bass (siakap)', '金目鲈'],
  1438: ['Spanish mackerel steak (tenggiri)', '马鲛鱼片'],
  1440: ['Big onion, imported (India)', '大洋葱（印度）'],
  1441: ['Big onion, imported (China)', '大洋葱（中国）'],
  1442: ['Shallots, imported (India)', '小红葱（印度）'],
  1443: ['Shallots, imported (China)', '小红葱（中国）'],
  1444: ['Shallots, imported (Myanmar)', '小红葱（缅甸）'],
  1445: ['Faiza Emas rice 5%', 'Faiza Emas 白米 5%'],
  1458: ['Cabbage, imported (Beijing)', '包菜（北京）'],
  1475: ['White pomfret fish', '白鲳鱼'],
  1476: ['Indian mackerel (kembung)', '甘望鱼'],
  1477: ['Short mackerel (mabung)', '短鲭鱼'],
  1479: ['Broccoli', '西兰花'],
  1481: ['Cauliflower', '花椰菜'],
  1482: ['Chinese cabbage, local', '大白菜（本地）'],
  1483: ['Fresh yellow noodles', '黄面'],
  1489: ['Tamarind with seeds', '亚参（有籽）'],
  1491: ['Thai glutinous rice (susu)', '泰国糯米（Susu）'],
  1492: ['Thai glutinous rice', '泰国糯米'],
  1507: ['Coca-Cola soda (can)', '可口可乐（罐装）'],
  1515: ['Heinz Farley\'s rusks', 'Heinz Farley\'s 婴儿饼干'],
  1517: ['Heinz apple puree', 'Heinz 苹果泥'],
  1524: ['Colgate ZigZag toothbrush (soft)', '高露洁 ZigZag 牙刷（软毛）'],
  1525: ['Oral-B Complete toothbrush (soft)', 'Oral-B 牙刷（软毛）'],
  1539: ['Harimau lemon cleaning cream', '老虎牌柠檬清洁膏'],
  1544: ['Adabi Chinese fried rice seasoning', 'Adabi 中式炒饭调料'],
  1545: ['Seri Aji anchovy fried rice seasoning', 'Seri Aji 江鱼仔炒饭调料'],
  1547: ['Pepsi cola soda (can)', '百事可乐（罐装）'],
  1550: ['Chicken drumsticks', '鸡腿（小腿）'],
  1551: ['Chicken breast', '鸡胸肉'],
  1552: ['Chicken thighs', '鸡大腿'],
  1553: ['Chicken whole leg', '全鸡腿'],
  1554: ['Red snapper fillet', '红鱼片'],
  1555: ['White prawns, farmed (vannamei)', '白虾（养殖）'],
  1556: ['Spinach (bayam)', '苋菜'],
  1558: ['Choy sum (sawi)', '菜心'],
  1559: ['Water spinach (kangkung)', '蕹菜'],
  1560: ['Kailan', '芥兰'],
  1562: ['Dried shrimp', '虾米'],
  1563: ['Dried squid', '苏东干'],
  1564: ['Garlic, imported (China)', '蒜头（中国）'],
  1568: ['Adabi fish curry powder', 'Adabi 鱼咖喱粉'],
  1570: ['Adabi meat and chicken curry powder', 'Adabi 肉类咖喱粉'],
  1572: ['Babas meat curry powder', 'Babas 肉类咖喱粉'],
  1577: ['Adabi soup spice powder', 'Adabi 汤料粉'],
  1581: ['Rambutan rice 5%', '红毛丹牌白米 5%'],
  1582: ['Jasmine rice 5%', 'Jasmine 白米 5%'],
  1583: ['Jati TWR super rice 5% (imported)', 'Jati TWR 超级白米 5%（进口）'],
  1584: ['Rice vermicelli, local', '米粉（本地）'],
  1585: ['Rice vermicelli, imported', '米粉（进口）'],
  1588: ['Brown sugar', '红糖'],
  1589: ['White sugar, coarse', '粗白糖'],
  1590: ['White sugar, fine', '幼白糖'],
  1595: ['Daisy corn oil', 'Daisy 粟米油'],
  1596: ['Mazola corn oil', 'Mazola 粟米油'],
  1597: ['Vecorn corn oil', 'Vecorn 粟米油'],
  1598: ['Red Eagle blended cooking oil', '红鹰牌混合食用油'],
  1600: ['Knife blended cooking oil', '刀标混合食用油'],
  1601: ['Buruh palm cooking oil', 'Buruh 纯棕榈食用油'],
  1602: ['Vesawit palm cooking oil', 'Vesawit 纯食用油'],
  1603: ['Windmill ghee blend', 'Windmill 酥油'],
  1604: ['Adabi tamarind, seedless', 'Adabi 无籽亚参'],
  1605: ['Fine salt', '幼盐'],
  1606: ['Lady\'s Choice smooth peanut butter', 'Lady\'s Choice 幼滑花生酱'],
  1610: ['M&S coconut milk', 'M&S 椰浆'],
  1611: ['Kara coconut milk', 'Kara 椰浆'],
  1612: ['Harmuni coconut milk', 'Harmuni 椰浆'],
  1613: ['Star Brand food essence (assorted)', '星牌食用香精（多种口味）'],
  1615: ['Anchor butter, salted', '安佳咸牛油'],
  1619: ['Dutch Lady instant milk powder', '子母牌速溶奶粉'],
  1628: ['Nestle Cerelac wheat and honey', '雀巢 Cerelac 小麦蜂蜜'],
  1630: ['Colgate Twister toothbrush (soft)', '高露洁 Twister 牙刷（软毛）'],
  1635: ['Nestle Coffee-mate', '雀巢咖啡伴侣'],
  1650: ['Lipton tea bags', '立顿茶包'],
  1651: ['Yeo\'s soy milk (carton)', '杨协成豆奶（盒装）'],
  1804: ['Chicken wings', '鸡翅'],
  1819: ['Galangal', '南姜'],
  1822: ['Vagas Tokou imported rice (Sabah)', 'Vagas Tokou 进口白米（沙巴）'],
  1823: ['TQR rice 5% (Sabah)', 'TQR 白米 5%（沙巴）'],
  1824: ['Kelisa Emas super rice (Sabah)', 'Kelisa Emas 超级白米（沙巴）'],
  1825: ['Sazarice Anggur super rice (imported)', 'Sazarice Anggur 超级白米（进口）'],
  1826: ['Sazarice Roda super rice (imported)', 'Sazarice Roda 超级白米（进口）'],
  1827: ['Muhibah wheat flour', 'Muhibah 面粉'],
  1832: ['Bao-Bao Golden rice (Sarawak)', '宝宝牌金米（砂拉越）'],
  1833: ['Uncle Tan premium rice', 'Uncle Tan 优质白米'],
  1849: ['Blue Key self-raising flour', 'Blue Key 自发面粉'],
  1852: ['Desa fresh milk', 'Desa 鲜奶'],
  1854: ['F&N Sun Valley cordial', 'F&N Sun Valley 浓缩饮料'],
  1870: ['Faiza wheat flour', 'Faiza 面粉'],
  1872: ['Lady\'s Choice mayonnaise', 'Lady\'s Choice 美乃滋'],
  1876: ['Downy fabric softener', 'Downy 衣物柔顺剂'],
  1879: ['7Up lemon lime soda (can)', '七喜柠檬汽水（罐装）'],
  1899: ['Dried chilli, curly', '干辣椒（卷）'],
  1900: ['Dried chilli, flat', '干辣椒（扁）'],
  1904: ['Dumex Dugro 3 (1–3 years)', '杜美 Dugro 3（1–3岁）'],
  1913: ['Imported beef, block', '进口牛肉（块）'],
  1914: ['Imported buffalo meat, block (India)', '进口水牛肉（块，印度）'],
  1915: ['Grouper fillet', '石斑鱼片'],
  1916: ['Diamond trevally fish (cermin)', '镜鱼'],
  1919: ['Large white prawns (20–30/kg)', '大白虾（每公斤20–30只）'],
  1921: ['Red tilapia', '红罗非鱼'],
  1923: ['Eggplant, round', '圆茄子'],
  1926: ['Green chilli (akar)', '青辣椒（Akar）'],
  1927: ['Red chilli (akar)', '红辣椒（Akar）'],
  1928: ['Calamansi lime', '酸柑'],
  1929: ['Fresh coconut milk (thick)', '新鲜椰浆（浓）'],
  1931: ['Big onion, imported (Pakistan)', '大洋葱（巴基斯坦）'],
  1937: ['Saji palm cooking oil', 'Saji 纯食用油'],
  1938: ['Saji palm cooking oil', 'Saji 纯食用油'],
  1939: ['Saji palm cooking oil', 'Saji 纯食用油'],
  1940: ['Alif palm cooking oil', 'Alif 纯食用油'],
  1941: ['Alif palm cooking oil', 'Alif 纯食用油'],
  1942: ['Alif palm cooking oil', 'Alif 纯食用油'],
  1944: ['Soybeans, imported', '黄豆（进口）'],
  1947: ['Royal baking powder (tin)', 'Royal 发粉（罐装）'],
  1951: ['3A Boy premium rice', '3A Boy 优质白米'],
  1953: ['Saji sweetened creamer', 'Saji 甜炼奶'],
  1955: ['Marigold low-fat strawberry yogurt', 'Marigold 低脂草莓酸奶'],
  1960: ['Farm Fresh dates milk', 'Farm Fresh 椰枣鲜奶'],
  1963: ['Anmum Essential step 4 (no added sugar)', '安满 Essential 4（无添加糖）'],
  1964: ['Quaker instant oats', '桂格即食燕麦'],
  1966: ['Milna baby rusks', 'Milna 婴儿饼干'],
  1976: ['Maggi curry instant noodles (5 pack)', '美极咖喱快熟面（5包）'],
  1984: ['Head & Shoulders shampoo', '海飞丝洗发水'],
  1987: ['Nivea Men deodorant', 'Nivea Men 止汗喷雾'],
  1988: ['Nivea deodorant (extra brightening)', 'Nivea 止汗喷雾（亮白）'],
  1989: ['Rexona Men deodorant', 'Rexona 男士止汗剂'],
  1990: ['Rexona deodorant (powder dry)', 'Rexona 止汗剂（干爽）'],
  1992: ['Attack washing powder', 'Attack 洗衣粉'],
  1998: ['Dettol multi-purpose cleaner', '滴露多用途清洁剂'],
  1999: ['Mr Muscle multi-purpose cleaner', 'Mr Muscle 多用途清洁剂'],
  2000: ['Ajax Fabuloso multi-purpose cleaner', 'Ajax Fabuloso 多用途清洁剂'],
  2001: ['Dumex Dupro 2 follow-on formula', '杜美 Dupro 2 较大婴儿配方奶粉'],
  2002: ['Clorox bleach', 'Clorox 漂白水'],
  2003: ['Rice vermicelli, imported', '米粉（进口）'],
  2004: ['Family super rice (imported)', 'Family 超级白米（进口）'],
  2009: ['Dutch Lady 123 growing-up milk', '子母牌 123 成长奶粉'],
  2010: ['Dutch Lady 456 growing-up milk', '子母牌 456 成长奶粉'],
  2011: ['Maggi tom yam stock cubes', '美极冬炎汤块'],
  2014: ['Enfagrow A+ Mind Pro step 3', 'Enfagrow A+ Mind Pro 3'],
  2019: ['Nescafe 3-in-1 coffee', '雀巢三合一咖啡'],
  2020: ['Lactel fat-free strawberry yogurt', 'Lactel 脱脂草莓酸奶'],
  2022: ['Buttercup spread', 'Buttercup 牛油抹酱'],
  2025: ['Everyday instant milk powder', 'Everyday 速溶奶粉'],
  2027: ['NAN step 1 infant formula', '雀巢 NAN 1 婴儿配方奶粉'],
  2030: ['NAN step 2 follow-on formula', '雀巢 NAN 2 较大婴儿配方奶粉'],
  2031: ['S-26 step 1 infant formula', 'S-26 1段婴儿配方奶粉'],
  2032: ['PetPet Gold+ diapers', 'PetPet Gold+ 纸尿片'],
  2036: ['Kuda Hijau wheat flour', '青马牌面粉'],
  2037: ['Longkou rice vermicelli', '龙口牌米粉'],
  2042: ['PetPet Gold+ diaper pants', 'PetPet Gold+ 拉拉裤'],
  2045: ['Sardines, fresh (selayang)', '沙丁鱼（新鲜）'],
  2047: ['Tuna (tongkol)', '吞拿鱼（Tongkol）'],
  2056: ['Axion dishwashing paste', 'Axion 洗碗膏'],
  2060: ['Marigold HL low-fat milk', 'Marigold HL 低脂牛奶'],
  2062: ['S-26 SMA step 1 infant formula', 'S-26 SMA 1段婴儿配方奶粉'],
  2066: ['Faiza Emas white rice (imported)', 'Faiza Emas 白米（进口）'],
  2068: ['Jasmine Super 5 Special rice (imported)', 'Jasmine Super 5 白米（进口）'],
  2086: ['Baby bok choy', '小白菜'],
  2087: ['White radish', '白萝卜'],
  2098: ['Drypers Wee Wee Dry diapers', 'Drypers Wee Wee Dry 纸尿片'],
  2099: ['Huggies Dry diapers', '好奇干爽纸尿片'],
  2100: ['Drypers Drypantz diaper pants', 'Drypers Drypantz 拉拉裤'],
  2101: ['Huggies Dry diaper pants', '好奇干爽拉拉裤'],
  2102: ['Lifebuoy body wash', '卫宝沐浴露'],
  2103: ['Dettol body wash', '滴露沐浴露'],
  2104: ['Fernleaf milk powder (1–3 years)', 'Fernleaf 奶粉（1–3岁）'],
  2105: ['Fernleaf milk powder (4–6 years)', 'Fernleaf 奶粉（4–6岁）'],
  2106: ['Rejoice shampoo', '飘柔洗发水'],
  2107: ['Potatoes, imported (Pakistan)', '马铃薯（巴基斯坦）'],
  2108: ['Sunsilk shampoo', '夏士莲洗发水'],
  2109: ['Breeze washing powder', 'Breeze 洗衣粉'],
  2110: ['Top laundry detergent', 'Top 洗衣剂'],
  2111: ['Daia washing powder', 'Daia 洗衣粉'],
  2112: ['Sunlight dishwashing liquid', 'Sunlight 洗碗精'],
  2113: ['Sunquick orange cordial', 'Sunquick 浓缩橙汁'],
  2114: ['Milo chocolate malt drink (refill pack)', '美禄（补充装）'],
  2115: ['Indocafe Original Blend coffee', 'Indocafe 原味咖啡粉'],
}
